### PR TITLE
Update create-high-availability-vm-with-sets.sh

### PR DESCRIPTION
**Pull request by ShawnKupfer**
Update script to function, as Ubuntu-LTS is no longer available

### CODE REVIEW

**Comment by mbender-ms** [comment]
@ShawnKupfer I saw the ado item assigned to me as the doc author using the script. I'm trying to track down an owner for the script. I have no authority or permissions as the doc author to move this script PR along, or commit any of the 6 PRs on this issue. I'll keep you posted.

**Comment by ShawnKupfer** [comment]
[like]  Shawn Kupfer (AQUENT LLC) reacted to your message:
________________________________

**Comment by mbender-ms** [comment]
Merge via https://github.com/MicrosoftDocs/mslearn-improve-app-scalability-resiliency-with-load-balancer/pull/12

**Comment by mbender-ms** [comment]
Merge via https://github.com/MicrosoftDocs/mslearn-improve-app-scalability-resiliency-with-load-balancer/pull/12

**Pull request closed without merging**
